const products=[
{id:'individual',name:'Combo Individual',cat:'Combos',price:9000,tag:'20 PEÇAS',image:'combos',crop:'combo1',description:'6 Hot Salmão · 6 Uramaki Salmão · 4 Nigiri Salmão · 2 Hossomaki Salmão · 2 Uramaki Kani Crocante.'},
{id:'especial',name:'Combo Especial',cat:'Combos',price:14000,tag:'30 PEÇAS',image:'combos',crop:'combo2',description:'10 Hot Salmão · 6 Uramaki Salmão · 4 Nigiri Salmão · 6 Hossomaki Salmão · 4 Uramaki Kani Crocante.'},
{id:'familia',name:'Combo Família',cat:'Combos',price:23000,tag:'50 PEÇAS',image:'combos',crop:'combo3',description:'15 Hot Salmão · 10 Uramaki Salmão · 6 Nigiri Salmão · 8 Hossomaki Salmão · 3 Joy (arroz, salmão e cream cheese) · 8 Uramaki Kani Crocante.'},
{id:'salmao',name:'Temaki de Salmão',cat:'Temakis',price:3900,image:'temakis',crop:'temaki',description:'Salmão fresco, cream cheese e cebolinha.',variants:[{name:'Cru',price:3900},{name:'Hot',price:4400}]},
{id:'atum',name:'Temaki de Atum',cat:'Temakis',price:4200,image:'temakis',crop:'atum',description:'Atum, tempero especial, cream cheese e cebolinha.'},
{id:'misto',name:'Temaki Misto',cat:'Temakis',price:4000,image:'temakis',crop:'misto',description:'Salmão e camarão, cream cheese e cebolinha.',variants:[{name:'Cru',price:4000},{name:'Hot',price:4500}]},
{id:'big-hot',name:'Big Hot',cat:'Big Hot',price:4600,image:'big-hot',crop:'big',description:'Arroz, salmão, cream cheese, molho especial, cebolinha e gergelim.'},
{id:'poke',name:'Poke',cat:'Poke',price:4990,image:'poke',crop:'poke',description:'Arroz, salmão, sunomuno, manga, batata-doce chips, couve crispy, gergelim e cebolinha.',extras:[{name:'Abacate',price:500},{name:'Camarão',price:1200}]}
];
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cart=[],current=null,qty=1,toastTimer;const $=s=>document.querySelector(s);
function renderProducts(cat='Todos'){const cats=['Combos','Temakis','Big Hot','Poke'].filter(c=>cat==='Todos'||c===cat);$('#products').innerHTML=cats.map(c=>`<section class="category-section"><div class="section-heading"><h3>${c}</h3><span>${products.filter(p=>p.cat===c).length} opções</span></div><div class="grid">${products.filter(p=>p.cat===c).map(p=>`<article class="card"><div class="food-image ${p.crop}"><img src="${p.image}.jpg" alt="${p.name} no cardápio Japa Sushi" loading="lazy">${p.tag?`<span class="piece-tag">${p.tag}</span>`:''}</div><div class="card-body"><h3>${p.name}</h3><p>${p.description}</p><div class="card-bottom"><div class="price">${p.variants?'<small>A partir de</small>':''}${money(p.price)}</div><button class="add-button" onclick="openProduct('${p.id}')" aria-label="Escolher ${p.name}">+</button></div></div></article>`).join('')}</div></section>`).join('')}
$('.categories').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;$('.categories .active').classList.remove('active');b.classList.add('active');renderProducts(b.dataset.cat)});
function closeDialog(id){document.getElementById(id).close()}
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
function openProduct(id){current=products.find(p=>p.id===id);if(!current)throw Error('Produto inválido');qty=1;$('#qty').textContent=qty;$('#item-note').value='';$('#product-content').innerHTML=`<h2>${current.name}</h2><p style="margin-top:12px;font-size:14px">${current.description}</p>${current.variants?`<fieldset><legend>Escolha o preparo</legend>${current.variants.map((v,i)=>`<label class="option"><input type="radio" name="variant" value="${i}" ${i===0?'checked':''}>${v.name}<span>${money(v.price)}</span></label>`).join('')}</fieldset>`:''}${current.extras?`<fieldset><legend>Adicionais <small>· opcionais</small></legend>${current.extras.map((v,i)=>`<label class="option"><input type="checkbox" name="extra" value="${i}">${v.name}<span>+ ${money(v.price)}</span></label>`).join('')}</fieldset>`:''}`;updateProductTotal();$('#product-dialog').showModal()}
function configuration(){let variant=current.variants?current.variants[Number($('#product-form input[name=variant]:checked').value)]:null;let extras=Array.from(document.querySelectorAll('#product-form input[name=extra]:checked')).map(e=>current.extras[Number(e.value)]);return {variant,extras,unit:(variant?variant.price:current.price)+extras.reduce((s,e)=>s+e.price,0)}}
function updateProductTotal(){$('#add-total').textContent=money(configuration().unit*qty)}
function quantity(change){qty=Math.max(1,Math.min(99,qty+change));$('#qty').textContent=qty;updateProductTotal()}
$('#product-form').addEventListener('change',updateProductTotal);
function addItem(p,quantity,variant,extras,note){if(!p||!Number.isInteger(quantity)||quantity<1||quantity>99)throw Error('Quantidade ou produto inválido');const unit=(variant?variant.price:p.price)+extras.reduce((s,e)=>s+e.price,0);cart.push({id:p.id,name:p.name,qty:quantity,variant:variant?.name||'',extras:extras.map(e=>({...e})),unit,note});updateCartBadge()}
$('#product-form').addEventListener('submit',e=>{e.preventDefault();const c=configuration();addItem(current,qty,c.variant,c.extras,$('#item-note').value.trim());closeDialog('product-dialog');$('#toast').textContent='Adicionado ao seu pedido';$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2400)});
function total(){return cart.reduce((s,i)=>s+i.unit*i.qty,0)}
function updateCartBadge(){document.querySelectorAll('.count').forEach(e=>e.textContent=cart.reduce((s,i)=>s+i.qty,0));$('#mobile-total').textContent=money(total())}
function openCart(){renderCart();$('#cart-dialog').showModal()}
function renderCart(){$('#checkout').hidden=!cart.length;$('#cart-items').innerHTML=cart.length?cart.map((i,n)=>`<div class="cart-item"><div class="cart-item-top"><strong>${i.name}${i.variant?' · '+i.variant:''}</strong><strong class="gold">${money(i.unit*i.qty)}</strong></div>${i.extras.length?`<p>Adicionais: ${i.extras.map(e=>`${e.name} (+ ${money(e.price)})`).join(', ')}</p>`:''}${i.note?`<p>Obs.: ${escapeHTML(i.note)}</p>`:''}<div class="cart-item-actions"><div class="stepper"><button onclick="changeCart(${n},-1)" aria-label="Diminuir quantidade de ${i.name}">−</button><span>${i.qty}</span><button onclick="changeCart(${n},1)" aria-label="Aumentar quantidade de ${i.name}">+</button></div><button class="remove" onclick="removeItem(${n})">Remover</button></div></div>`).join(''):'<div class="empty"><h3>Seu pedido está começando.</h3><p>Escolha seus favoritos no cardápio.</p><button class="primary" onclick="closeDialog(\'cart-dialog\')">Explorar cardápio</button></div>';$('#subtotal').textContent=money(total());$('#grand-total').textContent=money(total());updateCartBadge()}
function changeCart(n,change){cart[n].qty=Math.min(99,cart[n].qty+change);if(cart[n].qty<=0)cart.splice(n,1);renderCart()}
function removeItem(n){cart.splice(n,1);renderCart()}
function setMode(){const delivery=$('#checkout input[name=mode]:checked').value==='delivery';$('#address-fields').hidden=!delivery;$('#pickup-info').hidden=delivery;for(const name of ['street','number','neighborhood','city'])$('#checkout [name='+name+']').required=delivery;$('#delivery-title').textContent=delivery?'Entrega':'Retirada';$('#delivery-cost').textContent=delivery?'Grátis':'Sem taxa'}
document.querySelectorAll('[name=mode]').forEach(e=>e.addEventListener('change',setMode));
function buildMessage(data){const lines=['*NOVO PEDIDO — JAPA SUSHI*','',`*Cliente:* ${data.customer}`,''];cart.forEach(i=>{lines.push(`*${i.qty}× ${i.name}${i.variant?' — '+i.variant:''}*`);if(i.extras.length)lines.push('Adicionais por unidade: '+i.extras.map(e=>`${e.name} (+ ${money(e.price)})`).join(', '));lines.push(`Valor unitário: ${money(i.unit)}`,`Subtotal: ${money(i.unit*i.qty)}`);if(i.note)lines.push('Observação: '+i.note);lines.push('')});if(data.mode==='delivery')lines.push('*Entrega grátis*',`Endereço: ${data.street}, ${data.number}`,`Bairro: ${data.neighborhood}`,`Cidade: ${data.city}`,...(data.reference?['Complemento / referência: '+data.reference]:[]));else lines.push('*Retirada no local*','Por favor, envie o endereço para retirada.');if(data.notes)lines.push('','Observações do pedido: '+data.notes);lines.push('',`*Total: ${money(total())}*`,'','Aguardo a confirmação do pedido e as orientações de pagamento.');return lines.join('\n')}
$('#checkout').addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const d=Object.fromEntries(new FormData(e.currentTarget));for(const k of Object.keys(d))d[k]=d[k].trim();for(const k of ['customer',...(d.mode==='delivery'?['street','number','neighborhood','city']:[])])if(!d[k]){const el=e.currentTarget.elements[k];el.setCustomValidity('Preencha este campo.');el.reportValidity();el.addEventListener('input',()=>el.setCustomValidity(''),{once:true});return}const link=document.createElement('a');link.href='https://wa.me/5599933002190?text='+encodeURIComponent(buildMessage(d));link.target='_blank';link.rel='noopener';document.body.appendChild(link);link.click();link.remove()});
function openMenus(){if(!$('#menu-images').children.length)$('#menu-images').innerHTML=['combos','temakis','big-hot','poke'].map(n=>`<img src="${n}.jpg" alt="Cardápio original: ${n}" loading="lazy">`).join('');$('#menus-dialog').showModal()}
renderProducts();setMode();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const reg=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};reg({name:'read_menu',description:'Lê os produtos, preços em centavos e opções do cardápio.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({products})});reg({name:'stage_order_item',description:'Adiciona um item ao carrinho visível, sem enviar o pedido ou abrir o WhatsApp.',inputSchema:{type:'object',properties:{productId:{type:'string'},quantity:{type:'integer',minimum:1,maximum:99},variant:{type:'string'},extras:{type:'array',items:{type:'string'},uniqueItems:true},note:{type:'string',maxLength:400}},required:['productId','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const p=products.find(p=>p.id===input.productId);if(!p)throw Error('Produto inválido');const variant=p.variants?.find(v=>v.name===input.variant);if(p.variants&&!variant)throw Error('Escolha uma opção de preparo válida');if(!p.variants&&input.variant)throw Error('Este produto não tem variantes');const names=input.extras??[];if(!Array.isArray(names)||new Set(names).size!==names.length)throw Error('Adicionais inválidos');const extras=names.map(n=>{const e=p.extras?.find(e=>e.name===n);if(!e)throw Error('Adicional inválido');return e});if(input.note!==undefined&&(typeof input.note!=='string'||input.note.length>400))throw Error('Observação inválida');addItem(p,input.quantity,variant,extras,input.note||'');if($('#cart-dialog').open)renderCart();return {items:cart.length,total:total()}}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
